# Generated by Django 3.0.9 on 2021-01-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_create_tree_node_model"),
        ("sample_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprofile",
            name="systematics",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profiles",
                to="content.TreeNode",
                verbose_name="Steckbrief-Ebene",
            ),
        ),
    ]
