# Generated by Django 3.0.9 on 2021-01-09 02:26

from django.db import migrations
import solid_backend.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample_content', '0002_myprofile_systematics'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='my_concat',
            field=solid_backend.content.fields.ConcatCharField(
                blank=True,
                concat_choices=[
                    [(None, '---------'), (1, 1), (2, 2), (3, 3), (4, 4)],
                    [(None, '---------'), ('Bonbon/s', 'Bonbon/s'), ('Tüte/n Popcorn', 'Tüte/n Popcorn'), ('Plätzchen', 'Plätzchen'), ('Lutscher', 'Lutscher')]
                ],
                default='',
                max_length=600,
                seperators=[', ', ' und ']
            ),
        ),
    ]
