# Generated by Django 3.0.9 on 2021-01-09 02:31

from django.db import migrations

import solid_backend.content.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sample_content", "0003_myprofile_my_concat"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprofile",
            name="color",
            field=solid_backend.content.fields.FromToConcatField(
                blank=True,
                default="",
                from_choices=[
                    (None, "---------"),
                    ("blau", "blau"),
                    ("grün", "grün"),
                    ("gelb", "gelb"),
                    ("rot", "rot"),
                ],
                max_length=100,
                to_choices=[
                    (None, "---------"),
                    ("blau", "blau"),
                    ("grün", "grün"),
                    ("gelb", "gelb"),
                    ("rot", "rot"),
                ],
            ),
        ),
    ]
