# Generated by Django 3.0.9 on 2021-02-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_content", "0004_myprofile_color"),
    ]

    operations = [
        migrations.RenameModel("MyProfile", "SampleProfile"),
    ]
