# Generated by Django 3.0.9 on 2021-02-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
        ('sample_content', '0005_rename_myprofile_to_sampleprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleprofile',
            name='systematics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='systematics', to='content.TreeNode', verbose_name='Steckbrief-Ebene'),
        ),
    ]
