# Generated by Django 3.0.9 on 2021-02-11 13:14

from django.db import migrations


def populate_tree_node_with_systematics(apps, schema_editor):
    """
    Populate tree_node fields with systematics values.
    """
    SampleProfile = apps.get_model("sample_content", "SampleProfile")

    for obj in SampleProfile.objects.all():
        obj.tree_node = obj.systematics
        obj.save()


def populate_systematics_with_tree_node(apps, schema_editor):
    """
    Populate systematics fields with tree_node values.
    """
    SampleProfile = apps.get_model("sample_content", "SampleProfile")

    for obj in SampleProfile.objects.all():
        obj.systematics = obj.tree_node
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sample_content', '0007_add_sampleprofile_tree_node'),
    ]

    operations = [
        migrations.RunPython(
            populate_tree_node_with_systematics, populate_systematics_with_tree_node
        ),
    ]
