# Generated by Django 3.0.9 on 2021-02-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_content', '0008_populate_sampleprofile_tree_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleprofile',
            name='systematics',
        ),
    ]
