# Generated by Django 3.0.9 on 2022-02-17 17:58

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_treenode_name_attributes"),
        ("sample_content", "0010_auto_20210522_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleprofile",
            name="tree_node",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sampleprofile_related",
                related_query_name="sampleprofiles",
                to="content.TreeNode",
            ),
        ),
        migrations.CreateModel(
            name="SecondSampleProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("integer", models.IntegerField(default=0)),
                (
                    "tree_node",
                    mptt.fields.TreeForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="secondsampleprofile_related",
                        related_query_name="secondsampleprofiles",
                        to="content.TreeNode",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
