# Generated by Django 3.2.16 on 2023-06-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_content', '0011_auto_20220217_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleprofile',
            options={'verbose_name': 'EXAMPLE VERBOSE NAME'},
        ),
    ]
