# Generated by Django 3.2.19 on 2023-07-13 09:52

from django.db import migrations
import solid_backend.content.fields
import solid_backend.utils.drf_spectacular_extensions


class Migration(migrations.Migration):

    dependencies = [
        ('sample_content', '0012_alter_sampleprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondsampleprofile',
            name='my_md_field',
            field=solid_backend.utils.drf_spectacular_extensions.MDTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sampleprofile',
            name='my_concat',
            field=solid_backend.content.fields.ConcatCharField(blank=True, concat_choices=[[(None, '---------'), (1, 1), (2, 2), (3, 3), (4, 4)], [(None, '---------'), ('Bonbon/s', 'Bonbon/s'), ('Tüte/n Popcorn', 'Tüte/n Popcorn'), ('Plätzchen', 'Plätzchen'), ('Lutscher', 'Lutscher')]], default='', max_length=600, seperators=[', ', ' und '], verbose_name='My Concat verbose'),
        ),
    ]
