# Generated by Django 3.0.9 on 2021-07-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_object", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioVideoMediaObject",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("media_object.mediaobject",),
        ),
        migrations.CreateModel(
            name="ImageMediaObject",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("media_object.mediaobject",),
        ),
    ]
