# Generated by Django 3.0.9 on 2021-02-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0010_rename_slideshow_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slideshowimage", old_name="img", new_name="image",
        ),
    ]
