# Generated by Django 3.0.9 on 2022-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_assign_photograph_as_img_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswer",
            name="feedback_subsequences",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="range_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="range_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="range_step",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="range_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="ranking_position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="subsequences",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="tolerance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quizanswer",
            name="correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quizanswer",
            name="feedback_correct",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="quizanswer",
            name="feedback_incorrect",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="quizanswer",
            name="text",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="text (Markdown)"
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("SC", "Single Choice"),
                    ("MC", "Multiple Choice"),
                    ("TF", "True or False"),
                    ("RN", "Range"),
                    ("RG", "Ranking"),
                ],
                max_length=2,
            ),
        ),
    ]
