# Generated by Django 3.0.9 on 2022-03-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_auto_20220308_1744"),
    ]

    operations = [
        migrations.RemoveField(model_name="quizquestion", name="img",),
    ]
