# Generated by Django 3.0.9 on 2022-03-08 18:10

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('quiz', '0007_remove_quizquestion_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizQuestion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taggedquiz_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='new_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',blank=True, through='quiz.TaggedQuiz', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
