# Generated by Django 3.2.22 on 2025-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20220315_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
