# Generated by Django 3.2.22 on 2025-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizanswer_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='unit',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
