# Generated by Django 3.1a1 on 2020-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photograph", "0001_implement_photograph_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photograph",
            name="img_original_scale",
            field=models.FloatField(
                blank=True,
                help_text="Längenwert (in Meter) pro Pixel",
                null=True,
                verbose_name="scale",
            ),
        ),
    ]
