# Generated by Django 3.0.9 on 2022-02-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_fields_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'ordering': ('term',)},
        ),
    ]
