# Generated by Django 3.2.20 on 2025-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_auto_20220217_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryentry',
            name='tags',
            field=models.CharField(default='Glossar', max_length=100),
        ),
    ]
