# Generated by Django 3.0.9 on 2021-02-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_create_tree_node_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='is_top_level',
        ),
    ]
