# Generated by Django 3.0.9 on 2021-02-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_treenode_is_top_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treenode", old_name="node_name", new_name="name",
        ),
    ]
