# Generated by Django 3.0.9 on 2021-02-09 13:01

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_rename_treenode_info_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="treenode",
            options={"verbose_name": "Tree node", "verbose_name_plural": "Tree nodes"},
        ),
        migrations.AlterField(
            model_name="treenode",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="treenode",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                related_query_name="child",
                to="content.TreeNode",
            ),
        ),
    ]
